// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Y-rSEyTHITYcQC_y4JRh5AUaJZQgCsM',
    appId: '1:1009843677216:android:a69c006d431ff000e6f445',
    messagingSenderId: '1009843677216',
    projectId: 'todo-app-b2342',
    storageBucket: 'todo-app-b2342.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKj-QI6wrkpvTJTV5kKYl6o2JtlRtsh3k',
    appId: '1:1009843677216:web:2e064328525902b0e6f445',
    messagingSenderId: '1009843677216',
    projectId: 'todo-app-b2342',
    authDomain: 'todo-app-b2342.firebaseapp.com',
    databaseURL: 'https://todo-app-b2342-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-b2342.firebasestorage.app',
    measurementId: 'G-GM123ST5L8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKj-QI6wrkpvTJTV5kKYl6o2JtlRtsh3k',
    appId: '1:1009843677216:web:2e064328525902b0e6f445',
    messagingSenderId: '1009843677216',
    projectId: 'todo-app-b2342',
    authDomain: 'todo-app-b2342.firebaseapp.com',
    databaseURL: 'https://todo-app-b2342-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-b2342.firebasestorage.app',
    measurementId: 'G-GM123ST5L8',
  );
}
